# Generated by Django 4.1.3 on 2022-12-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_details_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='productID',
            field=models.IntegerField(default=0),
        ),
    ]
