# Generated by Django 4.1.3 on 2022-12-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_detail_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
