# Generated by Django 4.1.3 on 2022-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
