# Generated by Django 4.1.3 on 2022-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_detail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='postrecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
            ],
        ),
    ]
