# Generated by Django 4.1.3 on 2022-12-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_postrecharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='postrecharge',
        ),
    ]
