# Generated by Django 4.1.3 on 2022-12-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
