# Generated by Django 4.1.3 on 2022-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments_pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('number', models.IntegerField(null=True)),
                ('expiry', models.IntegerField(blank=True, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payments_post',
        ),
    ]
