# Generated by Django 4.1.3 on 2022-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_payments_pre_rename_payments_payments_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments_post',
        ),
        migrations.AlterField(
            model_name='payments_pre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
