# Generated by Django 4.1.3 on 2022-12-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0005_delete_payments_post_alter_payments_pre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments_post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('number', models.IntegerField(null=True)),
                ('expiry', models.IntegerField(blank=True, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
