# Generated by Django 4.1.3 on 2022-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrecharge',
            name='number',
            field=models.IntegerField(default=500, max_length=15),
        ),
    ]
