# Generated by Django 4.1.3 on 2022-12-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0002_postrecharge_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrecharge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postrecharge',
            name='number',
            field=models.IntegerField(default=78291300, max_length=15),
        ),
    ]
