# Generated by Django 4.1.3 on 2022-12-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0003_alter_postrecharge_id_alter_postrecharge_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postrecharge',
        ),
    ]
