# Generated by Django 4.1.3 on 2022-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postpaid', '0004_delete_postrecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='postrecharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=78291300, max_length=15)),
                ('operator', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
            ],
        ),
    ]
