# Generated by Django 4.1.3 on 2022-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('operator', models.CharField(max_length=15)),
            ],
        ),
    ]
