# Generated by Django 4.1.3 on 2022-12-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepaid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
